export const MAX_SCHEMA_ARCHIVE_BYTES = 20 * 1024 * 1024;
export const MAX_SCHEMA_ARCHIVE_FILE_ENTRIES = 1000;
export const MAX_SCHEMA_ARCHIVE_SCHEMA_FILES = 250;
export const MAX_SCHEMA_ARCHIVE_PATH_CODE_POINTS = 512;
export const MAX_SCHEMA_ARCHIVE_PATH_DEPTH = 32;
