export const schemaNodeKinds = [
  'schema',
  'globalElement',
  'localElement',
  'elementReference',
  'complexType',
  'simpleType',
  'attribute',
  'attributeReference',
  'attributeGroup',
  'attributeGroupReference',
  'group',
  'groupReference',
  'sequence',
  'choice',
  'all',
  'simpleContent',
  'complexContent',
  'elementWildcard',
  'attributeWildcard',
  'extension',
  'restriction',
  'list',
  'union',
  'facet',
  'enumeration',
  'builtInType',
  'identityConstraint',
  'selector',
  'field',
  'xsdNotation',
  'import',
  'include',
  'redefine',
  'xsdAnnotation',
  'xsdDocumentation',
  'xsdAppInfo',
  'xsdForeignElement',
  'xsdComment',
  'xsdProcessingInstruction',
  'xsdProlog',
  'dtdElement',
  'dtdContentModel',
  'dtdAttributeList',
  'dtdAttribute',
  'dtdEntity',
  'dtdParameterEntity',
  'dtdNotation',
  'dtdElementReference',
  'dtdConditionalSection',
  'dtdComment',
  'dtdProcessingInstruction',
  'dtdDependency',
] as const;

/**
 * Node kinds covered by the completed DTD/XSD/ZIP visualization matrix.
 * Task 17.4 deliberately keeps its source-first RELAX NG preview outside that
 * historical 221-row acceptance authority.
 */
export type CompleteVisualizationSchemaNodeKind =
  (typeof schemaNodeKinds)[number];

export const relaxNgPresentationNodeKinds = [
  'relaxNgSchema',
  'relaxNgGrammar',
  'relaxNgStart',
  'relaxNgDefinition',
  'relaxNgElement',
  'relaxNgAttribute',
  'relaxNgReference',
  'relaxNgExternalReference',
  'relaxNgInclude',
  'relaxNgPattern',
  'relaxNgNameClass',
] as const;

export const standaloneSchemaPreviewNodeKinds = relaxNgPresentationNodeKinds;

export type SchemaNodeKind =
  | CompleteVisualizationSchemaNodeKind
  | (typeof relaxNgPresentationNodeKinds)[number];

export const schemaEdgeKinds = [
  'contains',
  'typeOf',
  'extends',
  'restricts',
  'references',
  'usesAttribute',
  'usesAttributeGroup',
  'usesGroup',
  'substitutes',
  'imports',
  'includes',
  'usedBy',
  'contentModelMember',
  'contentModelReference',
  'referencesElementName',
  'referencesUndeclaredElementName',
  'appliesAttributesToElement',
  'attributeBelongsToList',
  'entityUsesNotation',
  'attributeAllowsNotation',
  'dependsOnResource',
  'commentAttachesTo',
  'sourceOrderAdjacent',
  'sourceDocumentOwns',
  'ownsComponent',
  'particleMember',
  'ownsAnonymousType',
  'referencesDeclaration',
  'ownsContent',
  'wildcardMember',
  'ownsTypeVariety',
  'ownsFacet',
  'derivesFrom',
  'listItemType',
  'unionMemberType',
  'ownsIdentityConstraint',
  'ownsSelector',
  'ownsField',
  'keyrefTargets',
  'notationConstraint',
  'ownsSchemaRelationship',
  'ownsAnnotation',
  'ownsAnnotationEntry',
  'ownsForeignContent',
  'ownsXmlMetadata',
  'dependsOnSchema',
  'redefinesSchema',
  'redefinesComponent',
  'chameleonNamespaceContext',
  'substitutionGroupMember',
  'dependencyCycleMember',
  'sharesDependency',
] as const;

export type SchemaEdgeKind = (typeof schemaEdgeKinds)[number];
