export const STANDARDS_MAX_PROJECT_FILES = 250;
export const STANDARDS_MAX_AGGREGATE_BYTES = 20 * 1024 * 1024;
export const STANDARDS_MAX_PATH_CODE_POINTS = 512;
export const STANDARDS_MAX_PATH_SEGMENTS = 32;
export const STANDARDS_MAX_RETAINED_DIAGNOSTICS = 500;
export const STANDARDS_WORKER_LIFETIME_MS = 30_000;
