export {
  STANDARDS_MAX_PROJECT_FILES as XERCES_MAX_PROJECT_FILES,
  STANDARDS_MAX_AGGREGATE_BYTES as XERCES_MAX_AGGREGATE_BYTES,
  STANDARDS_MAX_PATH_CODE_POINTS as XERCES_MAX_PATH_CODE_POINTS,
  STANDARDS_MAX_PATH_SEGMENTS as XERCES_MAX_PATH_SEGMENTS,
  STANDARDS_MAX_RETAINED_DIAGNOSTICS as XERCES_MAX_RETAINED_DIAGNOSTICS,
  STANDARDS_WORKER_LIFETIME_MS as XERCES_WORKER_LIFETIME_MS,
} from '../projectResources/limits';
export const XERCES_MAX_DEPENDENCY_DEPTH = 32;
