export const XERCES_MAX_PROJECT_FILES = 250;
export const XERCES_MAX_AGGREGATE_BYTES = 20 * 1024 * 1024;
export const XERCES_MAX_PATH_CODE_POINTS = 512;
export const XERCES_MAX_PATH_SEGMENTS = 32;
export const XERCES_MAX_DEPENDENCY_DEPTH = 32;
export const XERCES_MAX_RETAINED_DIAGNOSTICS = 500;
export const XERCES_WORKER_LIFETIME_MS = 30_000;
